[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "https://infallible-hamilton-4b06e8.netlify.app/*"
  [headers.values]
    X-Frame-Options = "same-origin"
    Access-Control-Allow-Origin = "*"
   