[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "frame-ancestors 'self' https://infallible-hamilton-4b06e8.netlify.app"